Import('env')
env = env.Clone(LIBS=Split('-lglfw -lGL -lGLEW'))

# TODO(clchiou): Better, but this is still problematic.
build_root = env['BUILD_ROOT']
libs = [build_root.File('graphics/libgraphics.a'),
        build_root.File('platform/linux/graphics/libplatform_graphics.a')]
source = Glob('*.cc') + libs

env.Program(target='pong', source=source)
